const ProfileActionTypes = {
  CREATE_PROFILE_START: 'CREATE_PROFILE_START',
  CREATE_PROFILE_SUCCESS: 'CREATE_PROFILE_SUCCESS',
  CREATE_PROFILE_FAILURE: 'CREATE_PROFILE_FAILURE',

  FETCH_CURRENT_PROFILE_START: 'FETCH_CURRENT_PROFILE_START',
  FETCH_CURRENT_PROFILE_SUCCESS: 'FETCH_CURRENT_PROFILE_SUCCESS',
  FETCH_CURRENT_PROFILE_FAILURE: 'FETCH_CURRENT_PROFILE_FAILURE'
};

export default ProfileActionTypes;
