const ExperienceActionTypes = {
  FETCH_EXPERIENCES_START: 'FETCH_EXPERIENCES_START',
  FETCH_EXPERIENCES_SUCCESS: 'FETCH_EXPERIENCES_SUCCESS',
  FETCH_EXPERIENCES_FAILURE: 'FETCH_EXPERIENCES_FAILURE',

  ADD_EXPERIENCE_START: 'ADD_EXPERIENCE_START',
  ADD_EXPERIENCE_SUCCESS: 'ADD_EXPERIENCE_SUCCESS',
  ADD_EXPERIENCE_FAILURE: 'ADD_EXPERIENCE_FAILURE'
};

export default ExperienceActionTypes;
